//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRental.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public int idmovies { get; set; }
        public string movie_title { get; set; }
        public int number_in_stock { get; set; }
        public double rental_daily_rate { get; set; }
        public int release_year { get; set; }
        public string image { get; set; }
    }
}
